name: Deploy and Stage on Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: ğŸ“ Install Dependencies
        run: |
          cd ./frontend
          npm install
          cd ../backend
          npm install

      - name: ğŸ“ Cache Project Modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            ./frontend/node_modules
            ./backend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  build:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4

      - name: ğŸ› ï¸ Build and Test Frontend
        run: |
          cd ./frontend
          npm run build --if-present
          npm run test --if-present

      - name: ğŸ› ï¸ Build and Test Backend
        run: |
          cd ./backend
          npm run build --if-present
          npm run test --if-present

      - name: ğŸ“¦ Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            ./frontend/build
            ./backend/build

  stage:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'staging'
    permissions:
      id-token: write

    steps:
      - name: ğŸ’¾ Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: ğŸ” Azure Auth and Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: ğŸš€ Stage Changes on Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'fsu-emr'
          slot-name: 'staging'
          package: ./backend/build